### ISSUE TITLE
Symbol missing

### ISSUE THREAD

**Issue by gmos** [Karijn/sensemakers-esp32#2]
Symbol ESP32-MINI-32 sits in a library in2tech.  This library is not part of the repo.
Kicad schema recovers the symbols from a cache but PCB editor looses all tracks.
Please include the library in the repo.

**Comment by Karijn** [comment]
i think this is solved now, an someone confirm this?

**Comment by Karijn** [comment]
i moved the in2tech library to a base directory, this should work now

**Comment by Karijn** [comment]
solved
